language: c
install:
- wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
sudo: true
env:
  matrix:
  - PACKAGE="mrmime" OCAML_VERSION=4.03 TESTS=true
  - PACKAGE="mrmime" OCAML_VERSION=4.04 TESTS=true
  - PACKAGE="mrmime" OCAML_VERSION=4.05 TESTS=true
  - PACKAGE="mrmime" OCAML_VERSION=4.06 TESTS=true
  - PACKAGE="mrmime" OCAML_VERSION=4.07 TESTS=true
